#lang sicp
(if (= 10 10)
    (display "correct")
    (display "wrong"))
(if (= 12 (+ 5 3 4))
    (display "correct")
    (display "wrong"))
(if (= 8 (- 9 1))
    (display "correct")
    (display "wrong"))
(if (= 3 (/ 6 2))
    (display "correct")
    (display "wrong"))
(if (= 6 (+ (* 2 4) (- 4 6)))
    (display "correct")
    (display "wrong"))

(define a 3)
(define b (+ a 1))

(if (= 19 (+ a b (* a b)))
    (display "correct")
    (display "wrong"))
(if (not (= a b))
    (display "correct")
    (display "wrong"))
(if (= 4 (if (and (> b a) (< b (* a b)))
    b
    a))
    (display "correct")
    (display "wrong"))
(if (= 16 (cond ((= a 4) 6)
      ((= b 4) (+ 6 7 a))
      (else 25)))
    (display "correct")
    (display "wrong"))
(if (= 6 (+ 2 (if (> b a) b a)))
    (display "correct")
    (display "wrong"))
(if (= 16 (* (cond ((> a b) a)
         ((< a b) b)
         (else -1))
   (+ a 1)))
    (display "correct")
    (display "wrong"))
